version: '3.7'
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

  estimate_db:
    image: postgres:15-alpine
    restart: always
    container_name: estimate_db
    ports:
      - '5588:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estimate
    volumes:
      - ./local/data/postgres/:/var/lib/postgresql/data
